/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  ASSET MAP — every file path used by the site lives here.
 *  To swap a render / model, change it in this file only.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 *  Images are served as responsive WebP variants generated by
 *      node scripts/optimize-images.mjs
 *  (sources stay untouched in /public/assets).
 */

export const MODEL = {
  /** Meshopt-compressed + texture-optimised copy of the supplied Sketchfab model (6 MB vs 42 MB). */
  bike: '/assets/model/mt09.glb',
  /** Original, untouched download — kept for reference, never loaded by the site. */
  original: '/assets/2025_yamaha_mt-09_sp_v4.glb',
} as const;

export type PictureId = 'shutterOff' | 'shutterOn' | 'front' | 'side' | 'threeQuarter' | 'brutalist' | 'coastal' | 'blackStudio';

export type Picture = {
  id: PictureId;
  /** Folder/filename stem inside /assets/img */
  stem: string;
  /** Native pixel size of the supplied render (used for aspect ratios + crop maths). */
  w: number;
  h: number;
  /** Widths that exist on disk. Last entry is the native size. */
  widths: number[];
  alt: string;
};

export const PICTURES: Record<PictureId, Picture> = {
  shutterOff: {
    id: 'shutterOff',
    stem: 'shutter-off',
    w: 2048,
    h: 1152,
    widths: [800, 1400, 2048],
    alt: 'The motorcycle facing camera in a concrete hangar, shutter closed, headlights lit',
  },
  shutterOn: {
    id: 'shutterOn',
    stem: 'shutter-on',
    w: 2096,
    h: 1184,
    widths: [800, 1400, 2096],
    alt: 'The motorcycle facing camera as the hangar shutter opens onto mist',
  },
  front: {
    id: 'front',
    stem: 'front',
    w: 2064,
    h: 1232,
    widths: [800, 1400, 2064],
    alt: 'Front view of the motorcycle on black',
  },
  side: {
    id: 'side',
    stem: 'side',
    w: 2064,
    h: 1232,
    widths: [800, 1400, 2064],
    alt: 'Left side profile of the motorcycle on black',
  },
  brutalist: {
    id: 'brutalist',
    stem: 'brutalist',
    w: 1920,
    h: 1280,
    widths: [800, 1400, 1920],
    alt: 'The motorcycle parked on a wet concrete platform among brutalist pillars at sunrise',
  },
  coastal: {
    id: 'coastal',
    stem: 'wet-concrete',
    w: 2016,
    h: 1264,
    widths: [800, 1400, 2016],
    alt: 'The motorcycle cutting through spray on a wet coastal road beneath sea cliffs',
  },
  blackStudio: {
    id: 'blackStudio',
    stem: 'black-studio',
    w: 2064,
    h: 1232,
    widths: [800, 1400, 2064],
    alt: 'The motorcycle in a black studio with a single soft light',
  },
  threeQuarter: {
    id: 'threeQuarter',
    stem: 'three-quarter',
    w: 1824,
    h: 1152,
    widths: [800, 1400, 1824],
    alt: 'Three-quarter view of the motorcycle in a dark studio',
  },
};

export const pictureSrc = (p: Picture, width = p.w) => `/assets/img/${p.stem}-${width}.webp`;
export const pictureSrcSet = (p: Picture) =>
  p.widths.map((w) => `${pictureSrc(p, w)} ${w}w`).join(', ');

/**
 * Crop rectangles, in fractions (0–1) of the SOURCE image: [x, y, w, h].
 * A crop is never a new file — the same render is reused and framed in CSS,
 * so the motorcycle stays 100 % consistent everywhere.
 * Tweak a number here and the layout + its labels move together.
 */
export type Crop = readonly [x: number, y: number, w: number, h: number];

export const CROPS = {
  // ── 3/4 studio view ────────────────────────────────────────────────
  tqFull: [0, 0, 1, 1],
  tqTank: [0.36, 0.2, 0.34, 0.3],
  tqExhaust: [0.09, 0.47, 0.26, 0.3],
  tqFrontWheel: [0.62, 0.5, 0.3, 0.5],
  tqRear: [0.04, 0.42, 0.42, 0.52],
  tqCockpit: [0.4, 0.02, 0.5, 0.36],

  // ── Side profile ───────────────────────────────────────────────────
  sideFull: [0, 0, 1, 1],
  sideStrip: [0.04, 0.16, 0.94, 0.62],
  sideEngine: [0.33, 0.42, 0.34, 0.42],
  sideFrontWheel: [0.06, 0.48, 0.28, 0.46],
  sideRear: [0.6, 0.3, 0.38, 0.62],
  sideTank: [0.33, 0.19, 0.3, 0.26],
  sideChain: [0.52, 0.54, 0.4, 0.34],
  sideDisc: [0.1, 0.6, 0.2, 0.23],

  // ── Front view ─────────────────────────────────────────────────────
  frontFull: [0, 0, 1, 1],
  frontCockpit: [0.22, 0.03, 0.56, 0.4],
  frontLower: [0.3, 0.32, 0.4, 0.62],
  frontHeadlight: [0.39, 0.16, 0.22, 0.2],
  frontTyre: [0.43, 0.5, 0.15, 0.46],
  frontRadiator: [0.36, 0.34, 0.28, 0.28],
  frontFairing: [0.3, 0.16, 0.4, 0.26],

  // ── Hangar renders ─────────────────────────────────────────────────
  hangarFull: [0, 0, 1, 1],
  hangarFloor: [0.05, 0.62, 0.9, 0.38],
  hangarArchitecture: [0, 0, 0.5, 0.78],
} as const satisfies Record<string, Crop>;

/**
 * Cinematic environments (section 07).
 * Only renders that actually exist are enabled. NIGHT CITY and MOUNTAIN ROAD are still
 * open slots — when you have those renders, drop them in
 * /public/assets, add them to scripts/optimize-images.mjs + PICTURES above, then
 * flip the matching entry below (`picture` + `enabled: true`).
 */
export type EnvironmentScene = {
  id: string;
  enabled: boolean;
  title: string;
  kicker: string;
  caption: string;
  picture: PictureId | null;
  crop: Crop;
  /** object-position for cover-fitting, keeps the bike framed on every aspect ratio */
  focus: string;
  /** where the title sits so it never covers the machine: bottom-left, top-left, top-right */
  copy: 'bl' | 'tl' | 'tr';
};

export const ENVIRONMENTS: EnvironmentScene[] = [
  {
    id: 'brutalist',
    enabled: true,
    title: 'Brutalist architecture',
    kicker: 'Location 01',
    caption: 'Poured concrete, first light, nothing to prove.',
    picture: 'brutalist',
    crop: [0, 0, 1, 1],
    focus: '50% 62%',
    copy: 'tl',
  },
  {
    id: 'threshold',
    enabled: true,
    title: 'The open door',
    kicker: 'Location 02',
    caption: 'The moment the outside arrives.',
    picture: 'shutterOn',
    crop: CROPS.hangarFull,
    focus: '50% 62%',
    copy: 'bl',
  },
  {
    id: 'coastal',
    enabled: true,
    title: 'Coastal road',
    kicker: 'Location 03',
    caption: 'Salt, spray and a surface that never quite dries.',
    picture: 'coastal',
    crop: [0, 0, 1, 1],
    focus: '50% 58%',
    copy: 'tr',
  },
  {
    id: 'studio',
    enabled: true,
    title: 'Black studio',
    kicker: 'Location 04',
    caption: 'Nothing left to hide behind.',
    picture: 'blackStudio',
    crop: [0, 0, 1, 1],
    focus: '50% 58%',
    copy: 'tl',
  },
  // ── Placeholders — add renders, set picture + enabled ──────────────
  { id: 'night-city', enabled: false, title: 'Night city', kicker: 'Location 05', caption: '', picture: null, crop: CROPS.tqFull, focus: '50% 50%', copy: 'bl' },
  { id: 'mountain', enabled: false, title: 'Mountain road', kicker: 'Location 06', caption: '', picture: null, crop: CROPS.tqFull, focus: '50% 50%', copy: 'bl' },
];

export const MODEL_CREDIT = {
  text: '“2025 Yamaha MT-09 SP V4” by VTX',
  href: 'https://sketchfab.com/3d-models/2025-yamaha-mt-09-sp-v4-cb5878baf5974167806eb8524d57f0b0',
  license: 'CC BY-NC-SA 4.0',
  licenseHref: 'http://creativecommons.org/licenses/by-nc-sa/4.0/',
} as const;
